name: Github Actions

on:
  push:
    branches: [main]
jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Build Project
        run: echo "Building project..."
  test:
     name: Test the backend
     needs: build
     runs-on: windows-latest

     steps:
       - name: Run Test
         run: echo "Running tests..."
